<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Platforms>AnyCPU;x86;x64</Platforms>
    <RootNamespace>libCanopenSimple</RootNamespace>
    <AssemblyName>libCanopenSimple</AssemblyName>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
    <PropertyGroup>
      <DefaultItemExcludes>$(DefaultItemExcludes);libCanOpenSimpleCLI\**</DefaultItemExcludes>
      <DefaultItemExcludes>$(DefaultItemExcludes);SimpleTest\**</DefaultItemExcludes>
        <DefaultItemExcludes>$(DefaultItemExcludes);DriverTest\**</DefaultItemExcludes>
        <DefaultItemExcludes>$(DefaultItemExcludes);canfestivaldrivers\**</DefaultItemExcludes>
    </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="SocketCANSharp" Version="0.13.0" />
  </ItemGroup>
</Project>